# Generated by Django 5.0.7 on 2024-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='satutes',
            field=models.IntegerField(choices=[(1, 'قيد التنفيذ'), (2, 'مكتمل'), (3, 'مؤجل'), (4, 'ملغي')], default=1),
        ),
    ]
